### ISSUE TITLE
General error with this package?

### ISSUE THREAD

**Issue by Tartouffe** [mireianievas/PySQM#4]
Plugged in the SQM-LU at the Raspi4, Installed the package, edited the config.py, created the temp dir, but when i tried to run it by python i got this:  

---
python -m pysqm
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/PySQM/pysqm/__main__.py", line 29, in <module>
    import pysqm.main as main
  File "pysqm/main.py", line 46, in <module>
    from pysqm.read import *
  File "pysqm/read.py", line 31, in <module>
    import numpy as np
ImportError: No module named numpy
---

Also tried 'python2 -m pysqm' and 'python2.7 -m pysqm' .. result was the same. 
What am i doing wrong?

**Comment by Tartouffe** [comment]
Can get it installed with the additional files from the fork https://github.com/jscheidtmann/PySQM
closed.
